matrix:
  - name: Markdown
    expect_match: false
    apsell:
      mode: en
    dictionary:
      wordlists:
        - .wordlist.txt
      output: wordlist.dic
      encoding: utf-8
    pipeline:
      - pyspelling.filters.markdown:
          markdown_extensions:
            - markdown.extensions.extra:
      - pyspelling.filters.html:
          comments: false
          attributes:
            - alt
          ignores:
            - ":matches(code, pre)"
            - "code"
            - "pre"
            - "blockquote"
    sources:
      - "*.md"
      - "_data/**/*.md"
      - "_includes/**/*.md"
      - "_posts/**/*.md"
      - "_ols-1/**/*.md"
      - "_ols-2/**/*.md"
      - "_ols-3/**/*.md"
      - "_ols-4/**/*.md"
      - "_ols-5/**/*.md"
      - "_ols-6/**/*.md"
      - "_ols-7/**/*.md"
      - "_ols-8/**/*.md"
