[tool.black]
line-length = 120
target-version = ['py38']
include = '\.pyi?$'

[tool.darker]
isort = true

[tool.ruff]
# Enable: pycodestyle errors (E), Pyflakes (F), flake8-bugbear (B),
# flake8-logging-format (G) and pyupgrade (UP)
select = ["E", "F", "B", "G", "UP"]
target-version = "py38"
# Exceptions:
# B008 Do not perform function calls in argument defaults (for FastAPI Depends and Body)
# B9 flake8-bugbear opinionated warnings
# E501 is line length (delegated to black)
# G* are TODOs
ignore = ["B008", "B9", "E501", "G001", "G002", "G004"]