name: Spellcheck Action
on: [push, pull_request]

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      # The checkout step
      - uses: actions/checkout@v3
      - uses: rojopolis/spellcheck-github-actions@0.27.0
        name: Spellcheck
        with:
          source_files: "README.md" "./*.md" "./_data/*.md"
          task_name: MarkdownCheck
